#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "gem_dating"

begin
  $stdout << GemDating.from_file(ARGV[0]).table_print << "\n"
  exit 0
rescue StandardError => e
  warn e.message
  warn e.backtrace
  exit 2
end
